MESSAGES = {
    'en': {
        'language_selected': "You have selected English.",
        "not_subscribed": "❗️You must subscribe to our channel first.",
        "subscribe_btn": "📢 Subscribe to channel",
        "check_btn": "✅ I've subscribed",
        "still_not_subscribed": "You still aren't subscribed.",
        "thanks_for_sub": "✅ Thanks! Subscription confirmed.",
        'welcome_message': "Welcome to the registration bot!",
        'prompt_name': "Please enter your full name:",
        'invalid_name_empty': "Name cannot be empty. Please enter your full name:",
        'prompt_age': "Please enter your age (e.g., 25):",
        'invalid_age': "Invalid age. Please enter a number between 1 and 99.",
        'prompt_gender': "Please select your gender:",
        'gender_male_label': "Male",
        'gender_female_label': "Female",
        'gender_selected': "You have selected: {gender}",
        'invalid_gender_input': "Please use the buttons to select your gender.",
        'prompt_field': "Please select your field of interest:",
        'field_selected': "You have selected: {field}",
        'invalid_field_input': "Please use the buttons to select your field of interest.",
        'question_prompt': "Question {question_num}: {question}",
        'empty_answer': "Your answer cannot be empty. Please provide an answer.",
        'answer_too_long': "Your answer is too long. Please keep it under {max_words} words.",
        'registration_complete': "Registration complete! Thank you.",
        'csv_save_error': "An error occurred while saving your data. Please try again later.",
        'telegram_notification_error': "An error occurred while sending notification. Please contact support.",
        'prompt_awards': "What are your awards? (IELTS, SAT, Olympiads, etc.). Please include scores/years. (50–80 words):",
        'invalid_awards_empty': "Awards cannot be empty. Please list them."
    },
    'uz': {
        'language_selected': "Siz O'zbek tilini tanladingiz.",
        "not_subscribed": "❗️Avvalo kanalimizga obuna bo'lishingiz kerak.",
        "subscribe_btn": "📢 Kanalga obuna bo'lish",
        "check_btn": "✅ Obuna bo'ldim",
        "still_not_subscribed": "Siz hali ham obuna emassiz.",
        "thanks_for_sub": "✅ Rahmat! Obunangiz tasdiqlandi.",
        'welcome_message': "Ro'yxatdan o'tish botiga xush kelibsiz!",
        'prompt_name': "Iltimos, ism-sharifingizni kiriting:",
        'invalid_name_empty': "Ism-sharif bo'sh bo'lishi mumkin emas. Iltimos, ism-sharifingizni kiriting:",
        'prompt_age': "Iltimos, yoshingizni kiriting (masalan, 25):",
        'invalid_age': "Noto'g'ri yosh. Iltimos, 1 dan 99 gacha bo'lgan son kiriting.",
        'prompt_gender': "Iltimos, jinsingizni tanlang:",
        'gender_male_label': "Erkak",
        'gender_female_label': "Ayol",
        'gender_selected': "Siz tanladingiz: {gender}",
        'invalid_gender_input': "Iltimos, jinsingizni tanlash uchun tugmachalardan foydalaning.",
        'prompt_field': "Iltimos, qiziqish sohangizni tanlang:",
        'field_selected': "Siz tanladingiz: {field}",
        'invalid_field_input': "Iltimos, qiziqish sohangizni tanlash uchun tugmachalardan foydalaning.",
        'question_prompt': "Savol {question_num}: {question}",
        'empty_answer': "Javobingiz bo'sh bo'lishi mumkin emas. Iltimos, javob bering.",
        'answer_too_long': "Javobingiz juda uzun. Iltimos, uni {max_words} so'zdan oshirmang.",
        'registration_complete': "Ro'yxatdan o'tish yakunlandi! Rahmat.",
        'csv_save_error': "Ma'lumotlaringizni saqlashda xatolik yuz berdi. Iltimos, keyinroq qayta urinib ko'ring.",
        'telegram_notification_error': "Xabar yuborishda xatolik yuz berdi. Iltimos, yordam uchun murojaat qiling.", 
        'prompt_awards': "Mukofotlaringiz qanday? (IELTS, SAT, olimpiadalar va boshqalar). Ballar/yillarni kiriting. (50–80 so‘z):",
        'invalid_awards_empty': "Mukofotlar bo'sh bo'lmasligi kerak. Iltimos, ularni yozing.",
    },
    'ru': {
        'language_selected': "Вы выбрали русский язык.",
        "not_subscribed": "❗️Сначала подпишитесь на наш канал.",
        "subscribe_btn": "📢 Подписаться на канал",
        "check_btn": "✅ Я подписался(ась)",
        "still_not_subscribed": "Вы всё ещё не подписаны.",
        "thanks_for_sub": "✅ Спасибо! Подписка подтверждена.",
        'welcome_message': "Добро пожаловать в бот регистрации!",
        'prompt_name': "Пожалуйста, введите ваше полное имя:",
        'invalid_name_empty': "Имя не может быть пустым. Пожалуйста, введите ваше полное имя:",
        'prompt_age': "Пожалуйста, введите ваш возраст (например, 25):",
        'invalid_age': "Неверный возраст. Введите число от 1 до 99.",
        'prompt_gender': "Пожалуйста, выберите ваш пол:",
        'gender_male_label': "Мужской",
        'gender_female_label': "Женский",
        'gender_selected': "Вы выбрали: {gender}",
        'invalid_gender_input': "Пожалуйста, используйте кнопки, чтобы выбрать пол.",
        'prompt_field': "Пожалуйста, выберите вашу сферу интересов:",
        'field_selected': "Вы выбрали: {field}",
        'invalid_field_input': "Пожалуйста, используйте кнопки, чтобы выбрать сферу интересов.",
        'question_prompt': "Вопрос {question_num}: {question}",
        'empty_answer': "Ответ не может быть пустым. Пожалуйста, введите ответ.",
        'answer_too_long': "Ваш ответ слишком длинный. Пожалуйста, уложитесь в {max_words} слов.",
        'registration_complete': "Регистрация завершена! Спасибо.",
        'csv_save_error': "Произошла ошибка при сохранении ваших данных. Повторите попытку позже.",
        'telegram_notification_error': "Произошла ошибка при отправке уведомления. Свяжитесь со службой поддержки.", 
        'prompt_awards': "Какие у вас награды? (IELTS, SAT, олимпиады и т.д.). Укажите баллы/годы. (50–80 слов):",
        'invalid_awards_empty': "Поле с наградами не может быть пустым. Пожалуйста, перечислите их.",
        'awards_too_long': "Слишком длинно. Уложитесь в {max_words} слов.",
    }
}

def get_text(lang: str, key: str) -> str:
    return MESSAGES.get(lang, MESSAGES['en']).get(key, f"Error: Text not found for '{key}' in '{lang}'")
